# vim: set ft=gitlab-ci ts=2


stages:
  - build
  - deploy


build:
  stage: build
  image: python:3.10-slim
  only:
    - main
  script:
    - PACKAGE_VERSION=$(python setup.py --version)
    - python3 -m pip install twine
    - python3 setup.py sdist
    - >
      TWINE_PASSWORD=${CI_JOB_TOKEN}
      TWINE_USERNAME=gitlab-ci-token
      python3 -m twine upload
      --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
      --skip-existing
      dist/*


pages:
  stage: deploy
  image: python:3.10-slim
  before_script:
    - |
      pip install \
        mkdocs \
        mkdocs-macros-plugin \
        mkdocs-material \
        mkdocs-material-extensions
  script:
  - mkdocs build --config-file mkdocs.yml --verbose --site-dir public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^(main)/
      when: always
